"""make team_lead_id nullable

Revision ID: 5702b6426e7e
Revises: 966424dc2e7f
Create Date: 2026-04-11 10:56:21.591485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5702b6426e7e'
down_revision: Union[str, Sequence[str], None] = '966424dc2e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
