"""add cascade delete

Revision ID: e72dc19bea8a
Revises: d12e9674c053
Create Date: 2026-04-18 16:24:29.610585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72dc19bea8a'
down_revision: Union[str, Sequence[str], None] = 'd12e9674c053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_company_id_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('channels_company_id_fkey'), 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_company_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_company_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_assignees_task_id_fkey'), 'task_assignees', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignees', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_company_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_company_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_company_id_fkey'), 'teams', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_company_id_fkey'), 'tasks', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'task_assignees', type_='foreignkey')
    op.create_foreign_key(op.f('task_assignees_task_id_fkey'), 'task_assignees', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_company_id_fkey'), 'projects', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_company_id_fkey'), 'comments', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key(op.f('channels_company_id_fkey'), 'channels', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_company_id_fkey'), 'attachments', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
